#!/usr/bin/env node
// Affiliate monetization audit (shared engine version).
// Joins the program catalog × a site's content × optional traffic → monetization gaps.
//
// Usage:
//   node scripts/affiliate-audit.mjs --content=../agenticpassiveincome/content --write
//   node scripts/affiliate-audit.mjs --content=./content --traffic=./traffic.json
//
// --content  dir scanned recursively for .md/.mdx (default ./content)
// --traffic  optional JSON { pages:[{path,visitors}] } to rank gaps by traffic
// --write    also write AUDIT.md next to the catalog

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs'
import { join, dirname, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const arg = (k, d) => process.argv.find((a) => a.startsWith(`--${k}=`))?.split('=')[1] ?? d
const CONTENT = arg('content', join(ROOT, 'content'))
const TRAFFIC = arg('traffic', '')
const doWrite = process.argv.includes('--write')

const catalog = JSON.parse(readFileSync(join(ROOT, 'data', 'programs.json'), 'utf8'))
const visitorsByPath = TRAFFIC && existsSync(TRAFFIC)
  ? new Map((JSON.parse(readFileSync(TRAFFIC, 'utf8')).pages || []).map((p) => [p.path.replace(/\/$/, ''), p.visitors]))
  : new Map()

const aliasHits = catalog.programs.map((p) => ({
  program: p,
  rx: new RegExp(`\\b(${(p.aliases || [p.tool]).map((a) => a.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})\\b`, 'i'),
}))

function walk(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir).flatMap((f) => {
    const full = join(dir, f)
    if (statSync(full).isDirectory()) return walk(full)
    return /\.mdx?$/.test(f) ? [full] : []
  })
}

const rows = []
for (const file of walk(CONTENT)) {
  const body = readFileSync(file, 'utf8')
  const slug = relative(CONTENT, file).replace(/\.mdx?$/, '').replace(/\\/g, '/')
  const visitors = visitorsByPath.get(`/${slug}`) || visitorsByPath.get(`/blog/${slug.split('/').pop()}`) || 0
  const payers = []
  for (const { program, rx } of aliasHits) {
    if (program.hasProgram && program.status === 'active' && !program.ourLink && rx.test(body)) payers.push(program)
  }
  if (payers.length) rows.push({ slug, visitors, payers })
}

const programScore = new Map()
for (const r of rows) for (const p of r.payers) {
  const c = programScore.get(p.tool) || { program: p, traffic: 0, posts: 0 }
  c.traffic += r.visitors; c.posts += 1; programScore.set(p.tool, c)
}
const joinFirst = [...programScore.values()].sort((a, b) => a.program.priority - b.program.priority || b.traffic - a.traffic)

const md = `# Affiliate Monetization Audit\n\n_Generated by affiliate-agent-skills \`scripts/affiliate-audit.mjs\` against \`${CONTENT}\`._\n\n## Join these programs first\n\n| # | Program | Commission | Recurring | Traffic | # posts | Signup |\n|---|---------|-----------|-----------|---------|---------|--------|\n${joinFirst.map((j, i) => `| ${i + 1} | ${j.program.tool} | ${j.program.commission} | ${j.program.recurring || '—'} | ${j.traffic} | ${j.posts} | ${j.program.signupUrl} |`).join('\n') || '| — | (no monetizable mentions found) | | | | | |'}\n\n## Posts to add links to\n\n| Post | Visitors | Monetizable mentions |\n|------|----------|----------------------|\n${rows.sort((a, b) => b.visitors - a.visitors).map((r) => `| \`${r.slug}\` | ${r.visitors || '—'} | ${r.payers.map((p) => p.tool).join(', ')} |`).join('\n') || '| — | | |'}\n\n> Disclosure: _${catalog.disclosure}_\n`

console.log(md)
if (doWrite) { writeFileSync(join(ROOT, 'AUDIT.md'), md); console.log(`\n[affiliate-audit] wrote ${join(ROOT, 'AUDIT.md')}`) }
